import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Navigation } from "@/components/Navigation";
import { Palette, Sparkles, Download, RefreshCw, Building2, Paintbrush, Type } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "@/hooks/use-toast";

const BrandGenerator = () => {
  const [businessName, setBusinessName] = useState("");
  const [industry, setIndustry] = useState("");
  const [description, setDescription] = useState("");
  const [style, setStyle] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedBrand, setGeneratedBrand] = useState<{
    tagline: string;
    colors: { name: string; hex: string }[];
    fonts: { heading: string; body: string };
    tone: string;
    logoUrl?: string;
  } | null>(null);

  const generateBrand = async () => {
    if (!businessName || !industry) {
      toast({
        title: "Missing Information",
        description: "Please enter your business name and industry.",
        variant: "destructive",
      });
      return;
    }

    setIsGenerating(true);

    try {
      // Generate brand identity using AI
      const { data, error } = await supabase.functions.invoke("chat", {
        body: {
          message: `Generate a complete brand identity for a business called "${businessName}" in the ${industry} industry. ${description ? `Business description: ${description}.` : ""} ${style ? `Preferred style: ${style}.` : ""}
          
          Respond ONLY with a JSON object in this exact format (no markdown, no code blocks, just pure JSON):
          {
            "tagline": "A catchy tagline for the brand",
            "colors": [
              {"name": "Primary", "hex": "#hexcode"},
              {"name": "Secondary", "hex": "#hexcode"},
              {"name": "Accent", "hex": "#hexcode"},
              {"name": "Background", "hex": "#hexcode"}
            ],
            "fonts": {
              "heading": "Font name for headings",
              "body": "Font name for body text"
            },
            "tone": "Description of the brand voice and tone"
          }`,
        },
      });

      if (error) throw error;

      // Parse the AI response
      const responseText = data.response;
      const jsonMatch = responseText.match(/\{[\s\S]*\}/);
      if (jsonMatch) {
        const brandData = JSON.parse(jsonMatch[0]);
        setGeneratedBrand(brandData);
        toast({
          title: "Brand Generated!",
          description: "Your brand identity has been created successfully.",
        });
      }

      // Generate logo
      const { data: logoData, error: logoError } = await supabase.functions.invoke("generate-logo", {
        body: {
          businessName,
          industry,
          style: style || "modern and professional",
          colors: generatedBrand?.colors?.map(c => c.hex).join(", ") || "",
        },
      });

      if (!logoError && logoData?.imageUrl) {
        setGeneratedBrand(prev => prev ? { ...prev, logoUrl: logoData.imageUrl } : null);
      }
    } catch (error) {
      console.error("Error generating brand:", error);
      toast({
        title: "Generation Failed",
        description: "Failed to generate brand identity. Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsGenerating(false);
    }
  };

  const downloadBrandKit = () => {
    if (!generatedBrand) return;

    const brandKit = `
╔══════════════════════════════════════════════════════════════╗
║                    BRAND IDENTITY KIT                        ║
║                      ${businessName}                         ║
╚══════════════════════════════════════════════════════════════╝

TAGLINE
═══════
${generatedBrand.tagline}

COLOR PALETTE
═════════════
${generatedBrand.colors.map(c => `${c.name}: ${c.hex}`).join("\n")}

TYPOGRAPHY
══════════
Heading Font: ${generatedBrand.fonts.heading}
Body Font: ${generatedBrand.fonts.body}

BRAND VOICE & TONE
══════════════════
${generatedBrand.tone}

${generatedBrand.logoUrl ? `\nLOGO URL\n════════\n${generatedBrand.logoUrl}` : ""}

───────────────────────────────────────────────────────────────
Generated by Cardinal Business Genie
Your AI Partner in Building Empires
───────────────────────────────────────────────────────────────
    `;

    const blob = new Blob([brandKit], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${businessName.replace(/\s+/g, "_")}_Brand_Kit.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-background">
      <Navigation />
      
      <main className="container mx-auto px-4 py-8">
        <div className="max-w-6xl mx-auto">
          {/* Header */}
          <div className="text-center mb-12">
            <div className="inline-flex items-center justify-center w-20 h-20 rounded-2xl bg-gradient-to-br from-primary/20 to-primary/5 border border-primary/20 mb-6">
              <Palette className="w-10 h-10 text-primary" />
            </div>
            <h1 className="text-4xl md:text-5xl font-bold text-foreground mb-4">
              Brand & Logo Generator
            </h1>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
              Create a complete brand identity with AI-generated logos, color palettes, and brand guidelines
            </p>
          </div>

          <div className="grid lg:grid-cols-2 gap-8">
            {/* Input Form */}
            <Card className="bg-card/50 backdrop-blur-sm border-border/50">
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Building2 className="w-5 h-5 text-primary" />
                  Business Details
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-6">
                <div className="space-y-2">
                  <label className="text-sm font-medium text-foreground">Business Name *</label>
                  <Input
                    placeholder="Enter your business name"
                    value={businessName}
                    onChange={(e) => setBusinessName(e.target.value)}
                    className="bg-background/50"
                  />
                </div>

                <div className="space-y-2">
                  <label className="text-sm font-medium text-foreground">Industry *</label>
                  <Select value={industry} onValueChange={setIndustry}>
                    <SelectTrigger className="bg-background/50">
                      <SelectValue placeholder="Select your industry" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="technology">Technology</SelectItem>
                      <SelectItem value="healthcare">Healthcare</SelectItem>
                      <SelectItem value="finance">Finance & Banking</SelectItem>
                      <SelectItem value="retail">Retail & E-commerce</SelectItem>
                      <SelectItem value="food">Food & Restaurant</SelectItem>
                      <SelectItem value="education">Education</SelectItem>
                      <SelectItem value="real-estate">Real Estate</SelectItem>
                      <SelectItem value="consulting">Consulting</SelectItem>
                      <SelectItem value="creative">Creative & Design</SelectItem>
                      <SelectItem value="fitness">Fitness & Wellness</SelectItem>
                      <SelectItem value="legal">Legal Services</SelectItem>
                      <SelectItem value="other">Other</SelectItem>
                    </SelectContent>
                  </Select>
                </div>

                <div className="space-y-2">
                  <label className="text-sm font-medium text-foreground">Business Description</label>
                  <Textarea
                    placeholder="Describe what your business does, your target audience, and values..."
                    value={description}
                    onChange={(e) => setDescription(e.target.value)}
                    className="bg-background/50 min-h-[100px]"
                  />
                </div>

                <div className="space-y-2">
                  <label className="text-sm font-medium text-foreground">Brand Style</label>
                  <Select value={style} onValueChange={setStyle}>
                    <SelectTrigger className="bg-background/50">
                      <SelectValue placeholder="Choose a style direction" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="modern-minimal">Modern & Minimal</SelectItem>
                      <SelectItem value="bold-vibrant">Bold & Vibrant</SelectItem>
                      <SelectItem value="elegant-luxury">Elegant & Luxury</SelectItem>
                      <SelectItem value="playful-fun">Playful & Fun</SelectItem>
                      <SelectItem value="professional-corporate">Professional & Corporate</SelectItem>
                      <SelectItem value="organic-natural">Organic & Natural</SelectItem>
                      <SelectItem value="tech-futuristic">Tech & Futuristic</SelectItem>
                      <SelectItem value="vintage-retro">Vintage & Retro</SelectItem>
                    </SelectContent>
                  </Select>
                </div>

                <Button
                  onClick={generateBrand}
                  disabled={isGenerating}
                  className="w-full bg-primary hover:bg-primary/90"
                  size="lg"
                >
                  {isGenerating ? (
                    <>
                      <RefreshCw className="w-5 h-5 mr-2 animate-spin" />
                      Generating Brand...
                    </>
                  ) : (
                    <>
                      <Sparkles className="w-5 h-5 mr-2" />
                      Generate Brand Identity
                    </>
                  )}
                </Button>
              </CardContent>
            </Card>

            {/* Generated Brand Preview */}
            <div className="space-y-6">
              {generatedBrand ? (
                <>
                  {/* Logo Preview */}
                  {generatedBrand.logoUrl && (
                    <Card className="bg-card/50 backdrop-blur-sm border-border/50">
                      <CardHeader>
                        <CardTitle className="flex items-center gap-2">
                          <Sparkles className="w-5 h-5 text-primary" />
                          Generated Logo
                        </CardTitle>
                      </CardHeader>
                      <CardContent>
                        <div className="aspect-square max-w-[300px] mx-auto rounded-xl overflow-hidden bg-background/50 border border-border/50">
                          <img
                            src={generatedBrand.logoUrl}
                            alt="Generated Logo"
                            className="w-full h-full object-contain"
                          />
                        </div>
                      </CardContent>
                    </Card>
                  )}

                  {/* Tagline */}
                  <Card className="bg-card/50 backdrop-blur-sm border-border/50">
                    <CardHeader>
                      <CardTitle className="flex items-center gap-2">
                        <Type className="w-5 h-5 text-primary" />
                        Tagline
                      </CardTitle>
                    </CardHeader>
                    <CardContent>
                      <p className="text-2xl font-semibold text-center text-foreground italic">
                        "{generatedBrand.tagline}"
                      </p>
                    </CardContent>
                  </Card>

                  {/* Color Palette */}
                  <Card className="bg-card/50 backdrop-blur-sm border-border/50">
                    <CardHeader>
                      <CardTitle className="flex items-center gap-2">
                        <Paintbrush className="w-5 h-5 text-primary" />
                        Color Palette
                      </CardTitle>
                    </CardHeader>
                    <CardContent>
                      <div className="grid grid-cols-2 gap-4">
                        {generatedBrand.colors.map((color, index) => (
                          <div key={index} className="space-y-2">
                            <div
                              className="h-20 rounded-lg border border-border/50"
                              style={{ backgroundColor: color.hex }}
                            />
                            <div className="text-center">
                              <p className="font-medium text-foreground">{color.name}</p>
                              <p className="text-sm text-muted-foreground uppercase">{color.hex}</p>
                            </div>
                          </div>
                        ))}
                      </div>
                    </CardContent>
                  </Card>

                  {/* Typography */}
                  <Card className="bg-card/50 backdrop-blur-sm border-border/50">
                    <CardHeader>
                      <CardTitle className="flex items-center gap-2">
                        <Type className="w-5 h-5 text-primary" />
                        Typography
                      </CardTitle>
                    </CardHeader>
                    <CardContent className="space-y-4">
                      <div className="p-4 bg-background/50 rounded-lg">
                        <p className="text-sm text-muted-foreground mb-1">Heading Font</p>
                        <p className="text-xl font-bold text-foreground">{generatedBrand.fonts.heading}</p>
                      </div>
                      <div className="p-4 bg-background/50 rounded-lg">
                        <p className="text-sm text-muted-foreground mb-1">Body Font</p>
                        <p className="text-lg text-foreground">{generatedBrand.fonts.body}</p>
                      </div>
                    </CardContent>
                  </Card>

                  {/* Brand Tone */}
                  <Card className="bg-card/50 backdrop-blur-sm border-border/50">
                    <CardHeader>
                      <CardTitle>Brand Voice & Tone</CardTitle>
                    </CardHeader>
                    <CardContent>
                      <p className="text-muted-foreground leading-relaxed">{generatedBrand.tone}</p>
                    </CardContent>
                  </Card>

                  {/* Download Button */}
                  <Button
                    onClick={downloadBrandKit}
                    className="w-full"
                    size="lg"
                    variant="outline"
                  >
                    <Download className="w-5 h-5 mr-2" />
                    Download Brand Kit
                  </Button>
                </>
              ) : (
                <Card className="bg-card/50 backdrop-blur-sm border-border/50 h-full min-h-[400px] flex items-center justify-center">
                  <CardContent className="text-center">
                    <Palette className="w-16 h-16 text-muted-foreground/50 mx-auto mb-4" />
                    <p className="text-xl font-medium text-muted-foreground">
                      Your brand identity will appear here
                    </p>
                    <p className="text-sm text-muted-foreground/70 mt-2">
                      Fill in your business details and click generate
                    </p>
                  </CardContent>
                </Card>
              )}
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default BrandGenerator;
